### ISSUE TITLE
Low CPU utilisation when using pre-generated index?

### ISSUE THREAD

**Issue by ksahlin** [ksahlin/strobealign#111] opened 2022-10-26 09:01 UTC
Hi @marcelm @johan-gson ,

I am currently doing local some benchmarks with [this script](https://github.com/ksahlin/alignment_evaluation/blob/master/scripts/benchmark_sa_versions.sh) on speed, memory, accuracy between v0.7.1 and master (commit 4735d37) on smaller datasets. I use 1 thread in all benchmarks.

I am observing a low CPU utilization (like 70-90%) and slow runtime whenever strobealign is run as 

```
strobealign -r read_length -i idx_path ref               # -r specified  to make sure index is built with same params as reads to be mapped
strobealign idx_path reads1 reads2
```

When I run v0.7.1 and master as `strobealign ref reads1 reads2` I do not observe this low utilisation, both versions have 99-100% CPU usage. I did rerun several times and made sure no swapping or other programs interfering.

Specifically, comparing master versions in prebuilt index mode:

```
Total time mapping: 22.7336 s.
Total time reading read-file(s): 0.138567 s.
Total time creating strobemers: 1.43874 s.
Total time finding NAMs (non-rescue mode): 14.3635 s.
Total time finding NAMs (rescue mode): 2.23196 s.
Total time sorting NAMs (candidate sites): 0.148613 s.
Total time reverse compl seq: 0 s.
Total time base level alignment (ssw): 3.85355 s.
Total time writing alignment to files: 0 s.
```

to all in once mode:

```
Total time mapping: 8.70625 s.
Total time reading read-file(s): 0.117365 s.
Total time creating strobemers: 1.17759 s.
Total time finding NAMs (non-rescue mode): 2.01729 s.
Total time finding NAMs (rescue mode): 1.90312 s.
Total time sorting NAMs (candidate sites): 0.120601 s.
Total time reverse compl seq: 0 s.
Total time base level alignment (ssw): 3.09937 s.
Total time writing alignment to files: 0 s.
```
We can see the slowdown happens almost solely in the  `finding NAMs` step. 

Could it be that when reading in the reference, the memory layout is not as good as when creating directly. I notice that we use two 'methods' `StrobemerIndex::read` `StrobemerIndex::populate`.

Table below for  `hg38_chr1_2_3` (containing chr1, chr2, and chr3 of hg38).  "Time" is referring to only alignment time, meaning starting time from then indexing is built/read in memory. All these results have been run 3 times and show the same slowdown. Other alignment stats are identical between the master in different modes.

Peak memory reduction looks good though :)

```
ref,read_length,tool,%-aligned,accuracy,time(sec),Mem(MB)

hg38_chr1_2_3,100,strobealign-v0.7.1,align,99.44,98.1,9.5,7624.31
hg38_chr1_2_3,100,strobealign-master,align,99.44,98.098,9.8,7568.55
hg38_chr1_2_3,100,strobealign-master-preindexed,align,99.44,98.098,21.45,5828.93

hg38_chr1_2_3,125,strobealign-v0.7.1,align,99.6115,98.5635,9.46,7630.73
hg38_chr1_2_3,125,strobealign-master,align,99.6115,98.561,9.18,7568.49
hg38_chr1_2_3,125,strobealign-master-preindexed,align,99.6115,98.561,23.16,6019.81

hg38_chr1_2_3,150,strobealign-v0.7.1,align,99.5665,98.629,9.01,7643.67
hg38_chr1_2_3,150,strobealign-master,align,99.5665,98.6305,11.02,7105.7
hg38_chr1_2_3,150,strobealign-master-preindexed,align,99.5665,98.6305,20.27,6144.03

hg38_chr1_2_3,250,strobealign-v0.7.1,align,99.4805,98.947,15.75,7686.23
hg38_chr1_2_3,250,strobealign-master,align,99.4805,98.9485,14.54,7568.71
hg38_chr1_2_3,250,strobealign-master-preindexed,align,99.4805,98.9485,25.82,6459.13
```

**Comment by marcelm** [comment] 2022-10-26 09:29
Do you get the same results in both cases?

**Comment by ksahlin** [comment] 2022-10-26 09:51
I do get the same exact results between the two master versions, if that is what you are referring to? This I made sure after realizing the issue with the pre-build index related to my issue #109 . small difference in accuracy with respect to version 0.7.1 I believe is due to the small bug fix that you made (is_fw_rev duplicated variable). This difference is however negligible. Some of the internal stats such as number of extend alignments, rescue are very slightly different, but this is also expected given the bug fix above.

**Comment by johan-gson** [comment] 2022-10-26 11:59
Hi Kristoffer and Marcel!

I had problems with some of the map_params being uninitialized before when
the index was read from file, causing different results sometimes, I think
in the function you are referring to. If I remember correctly, some of
those are calculated when generating the index. Might be good to double
check that they are exactly the same in the two cases. I cannot do much
right now, I have to focus on my Broad projects at the moment. If the
problem remains, remind me in a week or so and maybe I can dig a bit more.

Best,

Johan

Best,

Johan

**Comment by ksahlin** [comment] 2022-10-26 13:24
To give some specific details regarding the different results (which imo are negligible), for the 250PE reads. Re differnece is even smaller for other instances. This difference does not explain the runtime. If anything the master vesion should be faster (given the stats below.

(The results between master version with/without pre-building index are _identical_)

master version (pre-build index run):
```
Total mapping sites tried: 227768
Total calls to ssw: 39096
Calls to ksw (rescue mode): 3330
Did not fit strobe start site: 201
Tried rescue: 7233
Total time mapping: 25.313 s.
```

master version (index-align in once):
```
Total mapping sites tried: 227768
Total calls to ssw: 39096
Calls to ksw (rescue mode): 3330
Did not fit strobe start site: 201
Tried rescue: 7233
Total time mapping: 14.1203 s.
```

v0.7.1:
```
Total mapping sites tried: 230654
Total calls to ssw: 41625
Calls to ksw (rescue mode): 3344
Did not fit strobe start site: 363
Tried rescue: 7233
Total time mapping: 15.3059 s.
```

**Comment by johan-gson** [comment] 2022-10-26 14:11
Yeah, looks super similar. Is there a tool for logging memory swapping,
cache misses etc.? It seems you can do that with Valgrind (Cachegrind), at
least for cache misses, I have never used it though. You can read a short
text about it here:
https://courses.cs.washington.edu/courses/cse326/05wi/valgrind-doc/cg_main.html

But I don't know if it helps.

Best,

Johan

**Comment by ksahlin** [comment] 2022-10-26 15:38
I have very limited use of valgrind, will probably be too much overhead for me to start with. At least, I will wait for Marcel's assessment in the hope of that this may arise from a simpler issue.

**Comment by marcelm** [comment] 2022-10-26 21:45
> Do you get the same results in both cases?

Sorry, I should have been clearer: What I meant to ask was whether the results from using the pre-built index vs. not using it are the same. I want to make sure that the runtimes are not due to mismatching indexing parameters.

If the read lengths of the two invocations used are not the same, the stored index is used with wrong indexing parameters.

Running this
```
strobealign -r read_length -i idx_path ref
strobealign idx_path reads1 reads2
```
only works if the read_length you specified in the first command is the same as the one that StrobeAlign estimates from the reads in the second command.

For me, if I the indexing parameters do not match, most reads are marked as unmapped in the output.

If you specify `-r` (and use the same value) in both cases, the results should be identical.

**Comment by ksahlin** [comment] 2022-10-27 08:19
Yes, they were/are identical. I have now rerun the benchmark with the following commands, to make sure:

```
# V1: master pre-built
strobealign -r read_length -i idx_path ref
strobealign idx_path reads1 reads2

# V2: master all-in-one
strobealign -r read_length ref reads1 reads2

# v0.7.1
strobealign -r read_length ref reads1 reads2
```

SAM files identical for the V1 and V2 (performing `diff`). Timing results are still different as reported above.

(Meant to say "very limited experience with valgrind" :)

**Comment by marcelm** [comment] 2022-10-27 09:57
I haven’t been able to reproduce this with my test dataset, which is a *D. melanogaster* reference genome and the first 100'000 reads of SRR6055476. I even saw a reduction in runtime because reading the index from disk is faster than building it (as expected).

Can you put your reference and reads somewhere on rackham so that I can try it with the exact same data that you use?

**Comment by ksahlin** [comment] 2022-10-27 09:59
It occurs for larger references I think. I did not see this to the same extent in only chr21 or chr15.

Sort of brainstorming here: but I notice for the above benchmarked chr1_2_3 instance that the peak memory is significantly lower for the pre-generated index (5.8Gb) compared to running master version in one go (7.6Gb). According to the comment [here](https://github.com/ksahlin/StrobeAlign/blob/main/src/index.cpp#L301) the peak memory should not be different. 

Therefore, is it something with that the hash table is smaller and results in more collisions? Although going from 2 to 14 seconds for find_nams function is a bit extreme.

**Comment by ksahlin** [comment] 2022-10-27 10:03
I have shared the chr1_2_3 instance and reads of different lengths with you.

**Comment by johan-gson** [comment] 2022-10-27 11:04
Let me know if you can reproduce it Marcel, I can also try to reproduce it
on Windows in that case and investigate a bit. Very strange this.

Best,

Johan

Den tors 27 okt. 2022 06:03Kristoffer ***@***.***> skrev:

**Comment by marcelm** [comment] 2022-10-27 14:44
The CPU usage when using the pre-generated index is something like 91% compared to 99% when not using it, but I wouldn’t expect otherwise because there are so few reads that the I/O overhead from reading in the index from disk makes up a noticable portion of the total running time. But that is probably not what you are observing anyway because you see different numbers for "Total time mapping".

**Comment by ksahlin** [comment] 2022-10-27 19:50
I exactly followed the installation instructions [here](https://github.com/ksahlin/StrobeAlign#from-source). Besides, I run the same master version in two modes, where both-index-and-map version is still fast.

However, perhaps it's false alarm. What I now did was:

1. to restart my Macbook which hasn't been rebooted in like 3-4 weeks..  
2. In addition to the chr1_2_3 (first three chromosomes), I performed an additional benchmarks with two new instances: chr1_2.fa and chr1_2_3_4.fa (first two and first four chromosomes, respectively) to test if size of the index mattered.

The difference has now disappeared after the reboot with the following results:
```
ref,read_length,tool,%-aligned,accuracy,time(sec),Mem(MB)
hg38_chr1_2,75,strobealign-v0.7.1,align,99.184,97.3905,658,11.06,4545.48
hg38_chr1_2,75,strobealign-master,align,99.184,97.3925,658,11.99,4502.7
hg38_chr1_2,75,strobealign-master-preindexed,align,99.184,97.3925,658,11.87,3579.03
hg38_chr1_2_3,75,strobealign-v0.7.1,align,99.199,97.4105,685,11.75,7611.76
hg38_chr1_2_3,75,strobealign-master,align,99.199,97.4135,685,12.87,7568.44
hg38_chr1_2_3,75,strobealign-master-preindexed,align,99.199,97.4135,685,12.82,6351.31
hg38_chr1_2_3_4,75,strobealign-v0.7.1,align,99.226,97.4905,620,12.06,8361.92
hg38_chr1_2_3_4,75,strobealign-master,align,99.226,97.489,620,15.19,6534.07
hg38_chr1_2_3_4,75,strobealign-master-preindexed,align,99.226,97.489,620,14.54,6558.86

hg38_chr1_2,100,strobealign-v0.7.1,align,99.462,98.1285,718,7.69,4558.7
hg38_chr1_2,100,strobealign-master,align,99.462,98.1265,718,7.77,4502.77
hg38_chr1_2,100,strobealign-master-preindexed,align,99.462,98.1265,718,8.16,3602.83
hg38_chr1_2_3,100,strobealign-v0.7.1,align,99.44,98.1,754,8.54,7624.31
hg38_chr1_2_3,100,strobealign-master,align,99.44,98.098,754,9.02,7568.36
hg38_chr1_2_3,100,strobealign-master-preindexed,align,99.44,98.098,754,8.88,6374.33
hg38_chr1_2_3_4,100,strobealign-v0.7.1,align,99.424,98.0765,801,9.01,8374.79
hg38_chr1_2_3_4,100,strobealign-master,align,99.424,98.076,801,9.49,8319.13
hg38_chr1_2_3_4,100,strobealign-master-preindexed,align,99.424,98.076,801,11.19,6631.12
```

Perhaps my Macbook had so many programs open that had not been rebooted so that it did a lot of "smart organising"/swapping of the memory which resulted in the poor performance whenever the index was read from file? I am really just guessing because I have no idea. However, the slowdown was definitely present before and replicated for this read-index way of running.  


TODO: I will add the master version in both modes to my larger benchmark on rackham with four different genomes (drosophila, maize, human CHM13, and rye) and more reads to see what happens to runtime and memory.

**Comment by johan-gson** [comment] 2022-10-27 21:01
Nice that this seems to be solved now!

But very unexpected behavior...

Best,

Johan

**Comment by marcelm** [comment] 2023-01-31 10:11
Reading through the above, it appears to me we can close this. There have been many changes to the code affecting the on-disk index, threading, CPU flags etc. since October, so I would say it makes most sense to open a new issue with new measurements if we see the problem again.

**Closed by marcelm** 2023-01-31 10:11 UTC
