### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by TDDB-limagrain** [ksahlin/StrobeAlign#16] opened 2022-02-22 11:08 UTC
Hi @ksahlin ,
I am giving a try to strobealign v0.6. I was able to compile it correctly on my computing nodes.
Genome indexing works fine but in the PE mode, it crashes from the beginning of the mapping part:

```
...
Using rescue cutoff: 208
@SQ     SN:Chr01        LN:51433939
@SQ     SN:Chr04        LN:48048378
@SQ     SN:Chr08        LN:63048260
@SQ     SN:Chr11        LN:53580169
@SQ     SN:Chr09        LN:38250102
@SQ     SN:Chr05        LN:40923498
@SQ     SN:Chr02        LN:49670989
@SQ     SN:Chr10        LN:44302882
@SQ     SN:Chr07        LN:40041001
@SQ     SN:Chr06        LN:31236378
@SQ     SN:Chr03        LN:53438756
@PG     ID:strobealign  PN:strobealign  VN:0.6  CL:strobealign
Running PE mode
Mapping chunk of 1000000 query sequences...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)
```

This is strange, because running it in SE mode with either the forward or the reverse reads work perfectly.
Any idea about that possible issue?

Thanks!

**Comment by ksahlin** [comment] 2022-02-22 14:09
Hi @TDDB-limagrain ,

Ouch. I ran it on all my experiments before the release. Apparently, they did not catch this error.

You mentioned earlier that you cannot share the genome. Does the error occur if you map it to a public genome such as [this one](https://plants.ensembl.org/Phaseolus_vulgaris/Info/Annotation/#assembly)? (Which I think is the public genome that you mentioned earlier)

If so, since the bug occurred within the first million reads, it would be great if I could get the first million paired-end reads `head -n 4000000 reads.L.fq > bugfix.L.fq`, `head -n 4000000 reads.R.fq > bugfix.R.fq` and try it on the public genome.

Otherwise, detecting it will be more difficult, but I think that I know which region the error occurs at least.

Best,
K

**Comment by TDDB-limagrain** [comment] 2022-02-22 16:36
Here is the 100 000 first reads: 
[bugfix.L.fq.gz](https://github.com/ksahlin/StrobeAlign/files/8118384/bugfix.L.fq.gz)
[bugfix.R.fq.gz](https://github.com/ksahlin/StrobeAlign/files/8118389/bugfix.R.fq.gz)

I indeed tried with the public genome you mentioned, but experienced the same issue!
Could it be related with the way I compiled the source (I couldn't use the precompiled binaries due to some GLIBCXX issues)?

**Comment by ksahlin** [comment] 2022-02-22 20:54
Thanks, I could replicate the error so should not take long to fix.

**Comment by ksahlin** [comment] 2022-02-23 04:52
Hi @TDDB-limagrain,

I have fixed the bug and pushed it to master. It now completes on the 100k reads you sent.

Since you mention that you compile `strobealign` from source, could you pull the latest master commit, recompile and check if it runs on your full dataset?

If it completes, I will release this fix as v0.6.1.  The cause was not accounting for reads of different lengths within a pair if going into rescue mode. The great thing with your report was that it revealed an issue in the rescue mode which will lead to some more properly mapped read pairs.

Thanks!

**Comment by TDDB-limagrain** [comment] 2022-02-23 07:17
I successfully recompiled the program and it now runs like a charm!
I only had time to test it on the sample PE reads I shared, but I will give a try to the full sample today.
Thank you very much!

**Comment by ksahlin** [comment] 2022-02-23 10:44
great, I will push v0.6.1 and then close this issue.

**Comment by ksahlin** [comment] 2022-02-23 21:52
Added new release and therefore closing this issue.

**Closed by ksahlin** 2022-02-23 21:52 UTC
