### ISSUE TITLE
[E::read_ncigar] No CIGAR operations  issue

### ISSUE THREAD

**Issue by rudigaspardo** [ksahlin/strobealign#143] opened 2022-11-19 16:17 UTC
Hi,  I'm using strobealing to test alignment performance and I get this error from samtools view command with sam created by strobealign (see below command and output) The .fna reference file is _Homo sapiens chromosome 18, GRCh38.p14_ 
the sam creation was succesful, aligning with a fastq that is a pbsim simulated directly from the same NC000018.fna 
What am I doing wrong ?
Thanks in advance .

The command samtools view was:
 `samtools view -bS -T NC000018.fna strobealign_ps01_NC000018.sam -O BAM -o strobealign_ps01_NC000018.bam -@ 12`

and the output was 

```
samtools view: error reading file "NC000018.sam"
[E::read_ncigar] No CIGAR operations
samtools view: error closing "NC000018.sam": -5
```
This is the command and output of sam ceration with strobealign 

```
 /packages/StrobeAlign/build/strobealign NC000018.fna ps01_NC000018.fastq -o strobealign_ps01_NC000018.sam -t 12

Using
k: 23
s: 17
w_min: 5
w_max: 15
Read length (r): 10032
Maximum seed length: 278
Threads: 12
R: 2
Expected [w_min, w_max] in #syncmers: [5, 15]
Expected [w_min, w_max] in #nucleotides: [35, 105]
A: 2
B: 8
O: 12
E: 1
Time reading references: 0.965166 s

ref vector approximate size: 11481897
Ref vector actual size: 10783788
Time generating seeds: 2.99098 s

Time sorting seeds: 1.18937 s

Unique strobemers: 9922754
Total time generating flat vector: 4.18048 s

Flat vector size: 10783788
Total strobemers count: 10783788
Total strobemers occur once: 9840601
Fraction Unique: 0.991721
Total strobemers highly abundant > 100: 783
Total strobemers mid abundance (between 2-100): 81369
Total distinct strobemers stored: 9922754
Ratio distinct to highly abundant: 12672
Ratio distinct to non distinct: 120
Filtered cutoff index: 1984
Filtered cutoff count: 41


Total time generating hash table index: 0.584856 s

Total time indexing: 5.73055 s

Using rescue cutoff: 82
Running SE mode
Done!
Total mapping sites tried: 502929
Total calls to ssw: 502929
Calls to ksw (rescue mode): 0
Did not fit strobe start site: 1585
Tried rescue: 16813
Total time mapping: 91.5354 s.
Total time reading read-file(s): 13.2334 s.
Total time creating strobemers: 2.68648 s.
Total time finding NAMs (non-rescue mode): 0.603002 s.
Total time finding NAMs (rescue mode): 0.0492406 s.
Total time sorting NAMs (candidate sites): 0.0038492 s.
Total time reverse compl seq: 5.79428e-311 s.
Total time base level alignment (ssw): 3.01523 s.
Total time writing alignment to files: 6.92938e-310 s.
```

**Comment by ksahlin** [comment] 2022-11-19 19:12
Hi @rudigaspardo,

Thanks for testing strobealign. From the output, it looks like you are aligning long reads (median read length is 10,000bp).

Strobealign is currently only a short-read aligner tested for Illumina reads up to 2*500bp. I believe the error comes from the extension alignment we perform, which will stop if forced to aligning through contiguous long segments over 2kbp. 

We do have plans to extend strobealign to long-read alignment  to also perform long-read alignment issue #24.

If you have short reads to align we appreciate your feedback.

**Comment by marcelm** [comment] 2023-01-27 14:17
I’m cleaning up the list of open issues a bit at the moment. I’m going to close this issue as a duplicate of #24.

**Closed by marcelm** 2023-01-27 14:17 UTC
