### ISSUE TITLE
sam file format error

### ISSUE THREAD

**Issue by jianshu93** [ksahlin/StrobeAlign#3] opened 2021-11-22 02:04 UTC
Dear StrobeAlign author,

Use default settings, the mapping sam file output cannot be transformed into sorted bam file by samtools: 

(base) [jzhao399@atl1-1-02-003-9-r Competitive_mapping]$ time StrobeAlign -t 24 T4Aer_MAG.fasta T4AerOil_R1.fa T4AerOil_R2.fa
Using
n: 2
k: 22
s: 18
t: 24
R: 2
w_min: 6
w_max: 14
[w_min, w_max] under thinning w roughly corresponds to sampling from downstream read coordinates (under random minimizer sampling): [30, 70]
Time reading references: 7.76452 s

ref vector approximate size: 9290379
Ref vector actual size: 8664874
Unique strobemers: 8651483
Total time generating flat vector: 2.85387 s

Flat vector size: 8664874
Total strobemers count: 8664874
Total strobemers occur once: 8639067
Total strobemers highly abundant > 100: 0
Total strobemers mid abundance (between 2-100): 12415
Total distinct strobemers stored: 8651483
Ratio distinct to non distinct: 696
Filtered cutoff index: 1730
Filtered cutoff count: 2

Total time generating hash table index: 0.72899 s

Total time indexing: 11.3475 s

Using rescue cutoff: 4
Running PE mode
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 104.07, stddev: 124.369) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 96.6191, stddev: 175.71) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 90.6641, stddev: 208.097) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 117.778, stddev: 245.558) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 106.226, stddev: 274.345) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 101.158, stddev: 301.601) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 97.5571, stddev: 323.28) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 102.831, stddev: 345.341) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 109.84, stddev: 371.438) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 114.511, stddev: 392.006) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 117.354, stddev: 407.773) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 138.058, stddev: 426.87) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 114.614, stddev: 440.569) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 108.915, stddev: 452.172) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 132.276, stddev: 467.806) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 129.727, stddev: 483.589) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 109.746, stddev: 500.041) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 107.748, stddev: 512.066) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 107.68, stddev: 525.201) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 117.557, stddev: 539.586) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 107.239, stddev: 553.863) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 116.547, stddev: 566.07) 
Mapping chunk of 1000000 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 110.742, stddev: 578.011) 
Mapping chunk of 148502 query sequences... 
Estimated diff in start coordinates b/t mates, (mean: 110.161, stddev: 589.893) 
Total mapping sites tried: 13055987
Total calls to ksw: 3218137
Calls to ksw (rescue mode): 1276608
Did not fit strobe start site: 1776340
Tried rescue: 33208162
Total time mapping: 103.476 s.
Total time reading read-file(s): 25.1783 s.
Total time creating strobemers: 18.6664 s.
Total time finding NAMs (non-rescue mode): 3.60437 s.
Total time finding NAMs (rescue mode): 0.409914 s.
Total time sorting NAMs (candidate sites): 0.0890606 s.
Total time reverse compl seq: 0 s.
Total time extending alignment: 17.081 s.
Total time writing alignment to files: 5.61499 s.

real	1m55.191s
user	17m49.681s
sys	0m14.051s
(base) [jzhao399@atl1-1-02-003-9-r Competitive_mapping]$ ls -lhs mapped.sam 
7.3G -rw-r--r-- 1 jzhao399 p-ktk3 7.3G Nov 21 20:23 mapped.sam
(base) [jzhao399@atl1-1-02-003-9-r Competitive_mapping]$ samtools view -bS -@ 24 mapped.sam | samtools sort -@ 24 -O bam -o mapped_sorted.bam
samtools view: error reading file "mapped.sam": Input/output error
samtools view: error closing "mapped.sam": -5
[bam_sort_core] merging from 0 files and 24 in-memory blocks...

Any idea?

Thanks,

Jianshu

**Comment by ksahlin** [comment] 2021-11-22 09:43
Hi @jianshu93,

Perhaps it's that the query names are too long. Shortening the query names seems to solve it, see [this issue](https://github.com/nanoporetech/medaka/issues/284). Strobealign does not cut query names after the first space like some other aligners, I could implement this.

The "Input/output error" looks very general but the `-5` is supposed to give some hint. If you set ` --verbosity` to something higher than 3 (maybe 10) it may give you more information see [here](http://www.htslib.org/doc/samtools.html#GLOBAL_COMMAND_OPTIONS).  

If the above doesn't fix it; Do you get the same error for says a fraction of the first X lines of the SAM file? In that case, if you attach a subsample of the first X lines of it I can have a look.

Best,
Kristoffer

**Comment by ksahlin** [comment] 2021-11-22 09:53
Some other notes about your run:

* On this data, you can set -f 0.00000001 because you have very few repetitive seeds, and 0 highly repetitive seeds. This will improve quality
* It is interesting to note that reading fasta records from file is actually the most time-consuming step in your run (25 seconds). Perhaps this is because of disk latency or simply the consequence of parallelizing the computational steps (alignment).

how long are your reads?

best,
K

**Comment by jianshu93** [comment] 2021-11-22 23:54
Hi K
It's illumina short reads 150 bp. I subsampled the original reads for you. Reads are in interleaved format. You may need to split it using grep. 

Check here (shared via your institutional email for dropbox): https://www.dropbox.com/home/test_StrobeAlign_reads_assembly


Many thanks,

Jianshu

**Comment by ksahlin** [comment] 2021-11-23 08:20
Thanks, will have a look later today and get back to you!

**Comment by ksahlin** [comment] 2021-11-24 05:44
I detected the error. It's caused by a negative alignment coordinate (documented as a known bug here https://github.com/ksahlin/StrobeAlign/releases/tag/v0.0.3). I only observed the bug once (i.e., very rare) for alignments to the human genome but makes sense that it would appear when aligning to lots of contigs.

Will aim to fix it asap and get back to you. Thanks for the test case!

Best,
K

**Comment by ksahlin** [comment] 2021-11-30 16:39
I found and fixed the bug (pushed in commit 46f5fc44). I will push to master and create new binaries and a release later today.

I will let you know when it is ready and hope you could have a new go then. I could at least run 

`samtools view -bS T4AerOil_sbsmpl5.sam > T4AerOil_sbsmpl5.bam` after fixing the bug.

Also, I noted that your reads have quite variable length with many of them under 100nt. Strobealign is not good for such short reads with default parameters (recommended for reads >=150), but nevertheless good to get some feedback from your testing. 

Thanks!

**Comment by jianshu93** [comment] 2021-11-30 19:44
Hello Kristoffer,

Many thanks for the fix. I agree and yes we normally have > 150 bp but this is generated from an old machine, sequence length ranges from 100-150 bp. I will let you know with the new binaries testing. The bad thing for most sequencing machine is that reads are not always the same length, even for a 250 bp MiSeq, you can also have something around 100 bp out. But we will remove it during quality control. I could also filter the reads before doing mapping.

Thanks,

Jianshu

**Comment by jianshu93** [comment] 2021-11-30 21:01
Hello Kristoffer,

Everything looks fine but I have a small suggestion: remove the fasta annotation (only keep after > and before the first tab) from reference in sam output so that the sam output can be a little bit smaller. Or add an option to only keep them or an option to include annotation.

Jianshu

**Comment by ksahlin** [comment] 2021-11-30 22:08
I just uploaded binaries for Linux and Mac as well as a release.

Sure, I will consider that in the next implementation round.

Happy for any feedback on your experiments. The work on strobealign is just starting and it is of course desirable to increase performance for shorter (<150nt) reads among other things.

**Comment by ksahlin** [comment] 2021-11-30 22:10
I will close this issue now but please reopen it again or create a new one if there is still an issue.

Thanks!

**Closed by ksahlin** 2021-11-30 22:10 UTC
